"""Server code that handles physics simulation and communicates with remote IGVRClient objects."""


import numpy as np
from time import sleep

from PodSixNet.Channel import Channel
from PodSixNet.Server import Server


class IGVRChannel(Channel):
    """
    This is a server representation of a single, connected IGVR client.
    """
    def __init__(self, *args, **kwargs):
        Channel.__init__(self, *args, **kwargs)
    
    def Close(self):
        print(self, "Client disconnected")
        
    def Network_vrdata(self, data):
        print("Received VR data!")
        vr_data = np.array(data["vr_data"])
        print("Shape: {0}".format(vr_data.shape))
        
    def send_frame_data(self, frame_data):
        """
        Sends frame data to an IGVRClient.
        """
        print("Sending frame data of shape: {0}".format(frame_data.shape))
        # Convert numpy array to list so it can be sent
        # We are only really sending transform data, so converting to list is not so expensive
        self.Send({"action":"syncframe", "frame_data":frame_data.tolist()})
    

class IGVRServer(Server):
    """
    This is the IGVR server that handles communication with remote clients.
    """
    # Define channel class for the server
    channelClass = IGVRChannel
    
    def __init__(self, *args, **kwargs):
        """
        Initializes the IGVRServer.
        """
        Server.__init__(self, *args, **kwargs)
        print('Server launched')
        # This server manages a single vr client
        self.vr_client = None

    def register_renderer(self, renderer):
        """
        Register the renderer from which the server will collect frame data

        :param renderer: the renderer from which we extract visual data
        """
        self.renderer = renderer
    
    def Connected(self, channel, addr):
        """
        Called each time a new client connects to the server.
        """
        print("New connection:", channel)
        self.vr_client = channel
        
    def generate_frame_data(self):
        """
        Generates frame data to send to client
        """
        # TODO: Implement this and use self.renderer

        # Return a decent-sized array
        return np.random.rand(20,30)

    def send_frame(self):
        """
        Pumps the server to refresh incoming/outgoing connections.
        """
        self.Pump()
        frame_data = self.generate_frame_data()
        print('Frame data generated by the server:')
        print(frame_data.shape)

        # TODO: Implement the below:
        #if self.vr_client:
        #    self.vr_client.send_frame_data(frame_data)